name: 'Auto-Action-Readme'
version: 1.0.2
description: 'Github Action to use the settings in action.yml to populate the readme.'
inputs:
  output_file:
    description: "Output file name (default READMD.md)."
    default: 'README.md'
  commit_and_push:
    description: "Push back changes made to Github."
    default: 'true'
  tag:
    description: 'Tag or branch to use in example'
    default: 'main'
  comment:
    description: 'Comment after tag or branch to use in example'
    default: 'replace with specific tag or commit'

outputs:
  changes_detected:
    description: "Boolean if there were changes committed. Will be none if 'commit_and_push' was false."
    value: ${{ steps.push-new-data.outputs.changes_detected }}
  commit_hash:
    description: "Commit hash if new data has been committed. Will be none if 'commit_and_push' was false."
    value: ${{ steps.push-new-data.outputs.commit_hash }}

runs:
  using: "composite"
  steps:

    - name: Self warning
      uses: ajparsons/sha-version-warning@53c5e9cbf96afb276cb2cf486ebd45c5d5db0e11 #v 1.0.1
      with: 
        action_path: ${{ github.action_path }}

    - uses: ajparsons/cache-requirements-txt@f571ce408250d750c93659db28dd37f9272ce0a4
      id: cache-env
      with:
        requirements_path: "${{ github.action_path }}/requirements.txt" 
        cache_key: 'update-readme'
        venv_path: /tmp/auto-action-venv/
        python_version: "3.10"

    - name: Render readme
      id: render_readme
      shell: bash
      run: |
        source /tmp/auto-action-venv/bin/activate
        j2 ${{ github.action_path }}/readme-template.j2 action.yml --undefined > $OUTPUT_FILE
      env:
        OUTPUT_FILE: ${{ inputs.output_file }}
        TAG: ${{ inputs.tag }}
        COMMENT: ${{ inputs.tag }}

    - name: Remove double lines
      shell: python
      run: |
        import os
        from pathlib import Path
        p = Path(os.environ["OUTPUT_FILE"])
        t = p.read_text()
        while "\n\n\n" in t:
          t = t.replace("\n\n\n", "\n\n")
        p.write_text(t)
      env:
        OUTPUT_FILE: ${{ inputs.output_file }}

    - name: Push new data
      id: push-new-data
      if: ${{ inputs.commit_and_push == 'true' }}
      uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4.16.0
      with:
        commit_message: "Updated readme from action.yml"