# Update readme from action.yml
name: "Update readme"

permissions:
  contents: write
  packages: write

# don't allow multiple 'identical' processes to run. A second push should cancel the job from the first one.
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}-${{ github.event.inputs.pypi }}-${{ github.event.inputs.testpypi }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:

  update-action-meta:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ajparsons/get-yaml-value@e360e43a7c254b56590f07c95ec8b810f8575ed6
        id: get_version
        with:
          file: 'action.yml'
          key: 'version'

      - name: Update git tags
        id: update_tags
        uses: ajparsons/semver-to-tag@7705485fc6c01cb6bd4beea9837ede08d3e88594
        with:
          semver: ${{ steps.get_version.outputs.value }}
          update_tags: true

      - uses: ajparsons/auto-action-readme@main
        id: first-round-readme
        with:
          tag: ${{ steps.update_tags.outputs.patch_tag }}
          comment: Replace with commit hash for safety
          output_file: README.md
          commit_and_push: true

        # if this is the first time this version has been created, do a release
      - name: Release version
        if: ${{ steps.update_tags.outputs.tag_exists == 'false' }}
        shell: bash
        run: |
          gh release create $TAG --title $TAG
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ steps.update_tags.outputs.patch_tag }}

      - uses: ajparsons/auto-action-readme@main
        if: ${{ steps.first-round-readme.outputs.changes_detected }}
        with:
          tag: ${{ steps.first-round-readme.outputs.commit_hash }}
          comment: ${{ steps.update_tags.outputs.patch_tag }}
          output_file: README.md
          commit_and_push: true