# Update readme from action.yml
name: "Update readme"

# don't allow multiple 'identical' processes to run. A second push should cancel the job from the first one.
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}-${{ github.event.inputs.pypi }}-${{ github.event.inputs.testpypi }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:

  update-action-meta:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ajparsons/get-yaml-value@main
        id: get_version
        with:
          file: 'action.yml'
          key: 'version'

      - name: Update git tags
        id: tags
        uses: ajparsons/semver-to-tag@main
        with:
          semver: ${{ steps.get_version.outputs.value }}
          update_tags: true

      - uses: ajparsons/auto-action-readme@main
        with:
          tag: ${{ steps.tags.outputs.major_tag }}
          output_file: README.md

      - shell: bash
        name: debug step
        run: |
          echo "${{ steps.tags.outputs.tag_exist == 'false' }}"

        # if this is the first time this version has been created, do a release
      - name: Release version
        if: ${{ steps.tags.outputs.tag_exist == 'false' }}
        shell: bash
        run: |
          gh release create $TAG --title $TAG
        env:
          TAG: ${{ steps.tags.outputs.patch_tag }}
          